### ISSUE TITLE
install react router dom

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/areca-vestiaria#1]
install react router dom and then update App.js

**Comment by sbanati** [comment]
https://github.com/topcowmoo/areca-vestiaria/pull/6

**Comment by topcowmoo** [comment]
As per our discussion at the stand up please add the following pages and paths to main.jsx

Therapy
Physician Patient Resources
Guidelines
Borderline Personality Disorder
General Resources


Thanks!

**Comment by sbanati** [comment]
okay, thanks for adding that. I will add these and update the ticket

**Comment by sbanati** [comment]
https://github.com/topcowmoo/areca-vestiaria/pull/9
