### ISSUE TITLE
Search Bar Edit 1

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/areca-vestiaria#115]
In search bars, when we type a key word we get 5 items max, lets reduce this to top 3. 

![Image](https://github.com/user-attachments/assets/fa078f5b-2912-4cba-85fe-0675732b5dc4)

**Comment by topcowmoo** [comment]
![Image](https://github.com/user-attachments/assets/f3f75c0f-33de-4112-823f-9bd902788334)
![Image](https://github.com/user-attachments/assets/d46c50c7-3d91-4740-8181-eb4ce421620c)

**Comment by topcowmoo** [comment]
https://github.com/topcowmoo/areca-vestiaria/pull/121
