### ISSUE TITLE
Filter box and Directory Edit 1

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/areca-vestiaria#116]
![Image](https://github.com/user-attachments/assets/4a90bdb9-cafa-4db9-b7dd-8e0225abc7a6)

the space between the search bar and the filter box is large. We have reduced the amount of search results that show in the search drop down to 3. So lets now fix the spacing so filter box and directory fit properly

**Comment by topcowmoo** [comment]
![Image](https://github.com/user-attachments/assets/39054802-5c6a-49a7-a393-100022cbda36)
![Image](https://github.com/user-attachments/assets/b026f04e-7652-4645-9998-ada2007dff6f)
![Image](https://github.com/user-attachments/assets/0a2c7f85-2d76-4518-b655-71eb9d0976b7)
![Image](https://github.com/user-attachments/assets/8469c052-847f-4588-92cb-dda51eb01abe)

**Comment by topcowmoo** [comment]
https://github.com/topcowmoo/areca-vestiaria/pull/123
