### ISSUE TITLE
footer edit 1

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/areca-vestiaria#117]
company section has spacing pushing it in, fix alignment to other elements 

![Image](https://github.com/user-attachments/assets/454d3032-d923-4701-aad4-c2df07cb28f5)

**Comment by topcowmoo** [comment]
![Image](https://github.com/user-attachments/assets/652a209c-485f-4a9f-b348-00909b86ceec)
![Image](https://github.com/user-attachments/assets/c7624b0d-3a54-4840-bd09-0941a47f46d9)

**Comment by topcowmoo** [comment]
https://github.com/topcowmoo/areca-vestiaria/pull/122
