### ISSUE TITLE
image replacements

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/areca-vestiaria#127]
Therapy page 
Anger and Shame page 
Attachment and Emotions page 
Physician Page 

Contact us section needs new image 

Sunrise health and clinical excellence new image 

These pages need new images 

The reason for new images is because on mobile views the images did not look too good as they didnt focus properly

**Comment by topcowmoo** [comment]
![Image](https://github.com/user-attachments/assets/fbc19559-1c6f-4d3e-ad26-664d9d57694c)
![Image](https://github.com/user-attachments/assets/285ddd04-7c70-44f9-8426-30675217d938)
![Image](https://github.com/user-attachments/assets/6b2137fc-194d-4b70-9fb7-cba0fbf289a9)
![Image](https://github.com/user-attachments/assets/8f146764-ab9e-4582-a3e4-b3f7847f1ee2)
![Image](https://github.com/user-attachments/assets/2ec3e39d-e91e-43cc-b842-117d5e675f72)
