### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/areca-vestiaria#139]
![Image](https://github.com/user-attachments/assets/4b25c640-c970-4d1e-80f5-8abf3fd26f0d)

**Comment by topcowmoo** [comment]
![Image](https://github.com/user-attachments/assets/ac08c6ac-87c1-4855-bb31-4f86dbb9efd6)
![Image](https://github.com/user-attachments/assets/6a1d7f81-aaa6-459f-bd3b-9b8d6013064b)

**Comment by topcowmoo** [comment]
https://github.com/topcowmoo/areca-vestiaria/pull/156

**Comment by topcowmoo** [comment]
![Image](https://github.com/user-attachments/assets/133056cb-0e65-4c6f-8f0c-7a91bb8979d2)

**Comment by topcowmoo** [comment]
![Image](https://github.com/user-attachments/assets/dcb57109-f258-48ef-9d0b-08e05150879d)

**Comment by topcowmoo** [comment]
https://github.com/topcowmoo/areca-vestiaria/pull/168
