### ISSUE TITLE
Drop down menu on Resource nav bar

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/areca-vestiaria#140]
![Image](https://github.com/user-attachments/assets/a6cf23a1-2e57-49ab-86fa-81a27d506cb9)

**Comment by sbanati** [comment]
C:\Users\jsm_b\OneDrive\Documents\ShareX\Screenshots\2024-09\chrome_mc9R9UmoAP.gif

**Comment by sbanati** [comment]
![Image](https://github.com/user-attachments/assets/2a042e30-4b7e-4b62-84f2-6a8dd931c5d1)

**Comment by topcowmoo** [comment]
![Image](https://github.com/user-attachments/assets/02b30491-eaef-4076-9fd5-81429a7fd81b)

**Comment by topcowmoo** [comment]
https://github.com/topcowmoo/areca-vestiaria/pull/144
