### ISSUE TITLE
Resource button

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/areca-vestiaria#143]
![Image](https://github.com/user-attachments/assets/e5531b6b-f5cd-4cf8-bd81-f796899d4b67)

**Comment by sbanati** [comment]
There isnt much written here, so you might have to @ brandon in discord or leave reply in the exact comment in the figma mark up view and converse there for clarity.

**Comment by garrethil** [comment]
![Image](https://github.com/user-attachments/assets/00491b78-a2fb-48ad-bb24-c1fb6794dde6)
