### ISSUE TITLE
Directory Scale down

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/areca-vestiaria#150]
![Image](https://github.com/user-attachments/assets/9393a384-1408-4713-9a2b-027a120ffd93)

**Comment by sbanati** [comment]
![Image](https://github.com/user-attachments/assets/8c86a6fa-2693-4b03-8766-505d23f60f77)

**Comment by sbanati** [comment]
![Image](https://github.com/user-attachments/assets/f55f276d-b481-4abb-8868-aa7f2ab033bb)

**Comment by topcowmoo** [comment]
![Image](https://github.com/user-attachments/assets/74d558de-31bb-434e-8cbd-af07cab7a4f1)

tickets 147-150 are done in this branch. see commit messages for specifics

**Comment by topcowmoo** [comment]
https://github.com/topcowmoo/areca-vestiaria/pull/160
