### ISSUE TITLE
Search Bar styling

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/areca-vestiaria#152]
![Image](https://github.com/user-attachments/assets/0a2b130e-6774-4904-a7f2-129bc5560b3b)

**Comment by sbanati** [comment]
![Image](https://github.com/user-attachments/assets/2fb81c01-e279-4b7e-a7c0-f3be87e513e5)

**Comment by sbanati** [comment]
so fit the search bar to each title on each page, and then add the second images changes as well

**Comment by sbanati** [comment]
new development, dont change the search bar lengths , they are fine the way the are currently, focus on the highlight effect and the other examples shown above. Let me know if there is any confusion

**Comment by garrethil** [comment]
![Image](https://github.com/user-attachments/assets/7a88ba27-1222-4119-b5a3-89676e6933b0)
![Image](https://github.com/user-attachments/assets/7d29d717-b81c-4191-89d2-d95c979c0516)

I made the glow slightly reduce when user focuses on the bar and changed the text colour when no results are found. un sure of where to head with the animation, can look at it once I am clear on it.

**Comment by garrethil** [comment]
![Image](https://github.com/user-attachments/assets/b7d468ac-7605-4fc0-8750-da7bfa563ed5)
