### ISSUE TITLE
Directory changes

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/areca-vestiaria#153]
![Image](https://github.com/user-attachments/assets/823c7326-d964-410a-ad08-4117e274dbff)

**Comment by topcowmoo** [comment]
![Image](https://github.com/user-attachments/assets/fb5ce5bf-b06a-4867-b74b-22ac602d0e3c)
![Image](https://github.com/user-attachments/assets/9f4ca9d1-99a1-454c-9cf1-863cc1a67529)
![Image](https://github.com/user-attachments/assets/0453c86a-dd3f-4c5d-8073-f238db572a95)

**Comment by topcowmoo** [comment]
https://github.com/topcowmoo/areca-vestiaria/pull/170
