### ISSUE TITLE
filter box

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/areca-vestiaria#155]
![Image](https://github.com/user-attachments/assets/94babbc7-8122-43a8-9a96-40043b69cd89)

**Comment by sbanati** [comment]
![Image](https://github.com/user-attachments/assets/ab0654c8-3366-4a99-911d-4d327d9cfb48)

**Comment by topcowmoo** [comment]
removed custom checkmark and imported icon which should render the same across all browsers and os. Screenshots of full/mobile screens with changes for the three different filter boxes. 

![Image](https://github.com/user-attachments/assets/05401f16-9ada-4799-9e99-001b9fc2782c)
![Image](https://github.com/user-attachments/assets/966a7587-83f9-46d4-a5f3-6d28de55fe87)
![Image](https://github.com/user-attachments/assets/6ea433d1-8d80-4cd8-af10-7a0b7e36d9ec)
![Image](https://github.com/user-attachments/assets/eec7a8a7-c5f2-4c95-859c-3a7b355e5d66)
![Image](https://github.com/user-attachments/assets/be9747f5-22be-449d-9c05-4a62f841fa70)
![Image](https://github.com/user-attachments/assets/79fea190-3e96-40a6-8303-78bcedddb7c0)

**Comment by topcowmoo** [comment]
https://github.com/topcowmoo/areca-vestiaria/pull/162
