### ISSUE TITLE
commit search in searchbar. interaction with directory on pages. currently working fine on homepage

### ISSUE THREAD

**Issue by sbanati** [topcowmoo/areca-vestiaria#60]

**Comment by topcowmoo** [comment]
created new searchbarwithcommit for pages. new functionality of the searchbar includes results for specific page your on filtered by category. committing search by hitting enter key and by doing so the first resources in the searchbox results is opened in a new tab.

**Comment by topcowmoo** [comment]
example of one page for each different filter

![Image](https://github.com/user-attachments/assets/24a17c52-4081-471a-aacf-7dfdf5ead7b0)
![Image](https://github.com/user-attachments/assets/1c88b830-a54a-48c0-a21a-07801720679a)
![Image](https://github.com/user-attachments/assets/7c55da01-de28-4468-91cd-a3b46b458a78)

**Comment by topcowmoo** [comment]
https://github.com/topcowmoo/areca-vestiaria/pull/75
